# Generated by Django 3.1.5 on 2021-03-22 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='file',
            field=models.FileField(blank=True, upload_to='file'),
        ),
    ]
