# Generated by Django 3.1.5 on 2021-03-22 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0002_board_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file'),
        ),
        migrations.AlterField(
            model_name='board',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
