# Generated by Django 3.1.5 on 2021-03-22 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0003_auto_20210323_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='category',
            field=models.CharField(blank=True, choices=[('공지', '공지사항'), ('제품', '제품사항'), ('공통', '기타사항')], max_length=3, null=True),
        ),
    ]
