# Generated by Django 3.1.5 on 2021-03-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0004_board_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(blank=True, choices=[('공지', '공지'), ('제품', '제품'), ('공통', '공통')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='board',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
