# Generated by Django 3.1.5 on 2021-03-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0005_auto_20210323_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='content',
            field=models.TextField(blank=True, default='', null=True, verbose_name='CONTENT'),
        ),
    ]
