# Generated by Django 3.1.5 on 2021-03-24 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0006_auto_20210323_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(blank=True, choices=[('공지', '공지'), ('제품', '제품'), ('기타', '기타')], max_length=3, null=True),
        ),
    ]
