# Generated by Django 3.1.5 on 2021-03-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0007_auto_20210325_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='top_fixed',
            field=models.BooleanField(default=False, verbose_name='상단고정'),
        ),
    ]
