# Generated by Django 3.1.5 on 2021-03-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0008_board_top_fixed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='top_fixed',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='상단고정'),
        ),
    ]
