# Generated by Django 3.1.5 on 2021-03-29 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sp', '0009_auto_20210329_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='category',
            field=models.CharField(choices=[('공지', '공지'), ('제품', '제품'), ('기타', '기타')], default='공지', max_length=3),
        ),
    ]
